src/Entity/User.php
<?php
// src/App/Entity/User.php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
* @ORM\Table(name="app_users")
* @ORM\Entity(repositoryClass="App\Repository\UserRepository")
*/
class User implements UserInterface, \Serializable
{
/**
* @ORM\Column(type="integer")
* @ORM\Id
* @ORM\GeneratedValue(strategy="AUTO")
*/
private $id;

/**
* @ORM\Column(type="string", length=25, unique=true)
* @Assert\NotBlank(message="vul gebruikersnaam in")
*/
private $username;

/**
* @ORM\Column(type="string", length=255)
*/
private $password;

/**
* @ORM\Column(type="string", length=60, unique=false)
 *  @Assert\Email(
 *    message = "The email '{{ value }}' is geen geldig email adres")
 * @Assert\NotBlank(message="vul emailadres in")
*/
private $email;

/**
 * @Assert\Length(max=4096)
 * @Assert\NotBlank(message="vul wachtwoord in")
 */
private $plainPassword;

/**
 * @ORM\Column(type="json_array")
 */
private $roles = array();

/**
 * @ORM\Column(type="string", length=10)
 * @Assert\NotBlank(message="vul voorletters in")
 */
private $voorletters;

/**
 * @ORM\Column(type="string", length=10, nullable=true)
 */
private $tussenvoegsel;

/**
 * @ORM\Column(type="string", length=25)
 * @Assert\NotBlank(message="vul achternaam in")
 */
private $achternaam;

/**
 * @ORM\Column(type="string", length=25)
 * @Assert\NotBlank(message="vul adres in")
 *
 */
private $adres;

/**
 * @ORM\Column(type="string", length=7)
 * @Assert\NotBlank(message="vul postcode in")
 */
private $postcode;

/**
 * @ORM\Column(type="string", length=20)
 * @Assert\NotBlank(message="vul woonplaats in")
 */
private $woonplaats;
/**
 * @ORM\Column(type="string", length=15)
 *  @Assert\NotBlank(message="vul telfoonnummer in")
 */
private $telefoon;


public function getId()
{
    return $this->id;
}

function getNaam()
{
    return $this->voorletters." ".$this->tussenvoegsel." ".$this->achternaam;
}
/**
 * @return mixed
 */
public function getVoorletters()
{
    return $this->voorletters;
}

/**
 * @param mixed $voorletters
 */
public function setVoorletters($voorletters)
{
    $this->voorletters = $voorletters;
}

/**
 * @return mixed
 */
public function getTussenvoegsel()
{
    return $this->tussenvoegsel;
}

/**
 * @param mixed $tussenvoegsel
 */
public function setTussenvoegsel($tussenvoegsel)
{
    $this->tussenvoegsel = $tussenvoegsel;
}

/**
 * @return mixed
 */
public function getAchternaam()
{
    return $this->achternaam;
}

/**
 * @param mixed $achternaam
 */
public function setAchternaam($achternaam)
{
    $this->achternaam = $achternaam;
}

/**
 * @return mixed
 */
public function getAdres()
{
    return $this->adres;
}

/**
 * @param mixed $adres
 */
public function setAdres($adres)
{
    $this->adres = $adres;
}

/**
 * @return mixed
 */
public function getPostcode()
{
    return $this->postcode;
}

/**
 * @param mixed $postcode
 */
public function setPostcode($postcode)
{
    $this->postcode = $postcode;
}

/**
 * @return mixed
 */
public function getWoonplaats()
{
    return $this->woonplaats;
}

/**
 * @param mixed $woonplaats
 */
public function setWoonplaats($woonplaats)
{
    $this->woonplaats = $woonplaats;
}

/**
 * @return mixed
 */
public function getTelefoon()
{
    return $this->telefoon;
}

/**
 * @param mixed $telefoon
 */
public function setTelefoon($telefoon)
{
    $this->telefoon = $telefoon;
}


/**
 * Many Users have Many Activities.
 * @ORM\ManyToMany(targetEntity="Activiteit", inversedBy="users")
 * @ORM\JoinTable(name="deelnames")
 */
private $activiteiten;

public function __construct()
{
    $this->activiteiten = new \Doctrine\Common\Collections\ArrayCollection();
    $this->isActive = true;
}

public function addActiviteit(Activiteit $a)
{
    if ($this->activiteiten->contains($a)) {

        return;
    }

    $this->activiteiten->add($a);

}

public function removeActiviteit(Activiteit $a)
{
    if (!$this->activiteiten->contains($a)) {
        return;
    }
    $this->activiteiten->removeElement($a);
}
public function getEmail()
{
    return $this->email;
}

public function setEmail($email)
{
    $this->email = $email;
}

public function getUsername()
{
    return $this->username;
}

public function setUsername($username)
{
    $this->username = $username;
}

public function getPassword()
{
    return $this->password;
}

public function setPassword($password)
{
    $this->password = $password;
}

public function getPlainPassword()
{
    return $this->plainPassword;
}

public function setPlainPassword($password)
{
    $this->plainPassword = $password;
}

public function getSalt()
{
    // you *may* need a real salt depending on your encoder
    // see section on salt below
    return null;
}

public function getRoles()
{
    $roles = $this->roles;
    //$roles[] = 'ROLE_USER';

    return array_unique($roles);
}
public function setRoles(array $roles)
{
    $this->roles = $roles;

    // allows for chaining
    return $this;
}

public function eraseCredentials()
{
}

/** @see \Serializable::serialize() */
public function serialize()
{
return serialize(array(
$this->id,
$this->username,
$this->password,
// see section on salt below
// $this->salt,
));
}

/** @see \Serializable::unserialize() */
public function unserialize($serialized)
{
list (
$this->id,
$this->username,
$this->password,
// see section on salt below
// $this->salt
) = unserialize($serialized);
}
}

src/Controller/BezoekerController.php
<?php

namespace App\Controller;

use App\Entity\Soortactiviteit;
use App\Entity\User;
use App\Form\ActiviteitType;
use App\Form\SoortActiviteitType;
use App\Form\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class BezoekerController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction()
    {

        return $this->render('bezoeker/index.html.twig',array('boodschap'=>'Welkom'));
    }

    /**
     * @Route("/kartactiviteiten", name="kartactiviteiten")
     */
    public function kartactiviteitenAction()
    {
        $repository=$this->getDoctrine()->getRepository(Soortactiviteit::class);
        $soortactiviteiten=$repository->findAll();
        return $this->render('bezoeker/kartactiviteiten.html.twig',array('boodschap'=>'Welkom','soortactiviteiten'=>$soortactiviteiten));
    }

    /**
     * @Route("registreren", name="registreren")
     */
    public function registreren(Request $request,UserPasswordEncoderInterface $passwordEncoder)
    {
        // 1) build the form
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->add('save', SubmitType::class, array('label'=>"registreren"));
        // 2) handle the submit (will only happen on POST)
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            // 2.5) Is the user new, gebruikersnaam moet uniek zijn
            $repository=$this->getDoctrine()->getRepository(User::class);
            $bestaande_user=$repository->findOneBy(['username'=>$form->getData()->getUsername()]);

            if($bestaande_user==null)
            {
                // 3) Encode the password (you could also do this via Doctrine listener)
                $password = $passwordEncoder->encodePassword($user, $user->getPlainPassword());
                $user->setPassword($password);
                $user->setRoles(['ROLE_USER']);
                // 4) save the User!
                $em = $this->getDoctrine()->getManager();
                $em->persist($user);
                $em->flush();

                $this->addFlash(
                    'notice',
                    $user->getNaam().' is geregistreerd!'
                );

                return $this->redirectToRoute('homepage');
            }
            else
            {
                $this->addFlash(
                    'error',
                    $user->getUsername()." bestaat al!"
                );
                return $this->render('bezoeker/registreren.html.twig', [
                    'form'=>$form->createView()
                ]);
            }
        }

        return $this->render('bezoeker/registreren.html.twig', [
            'form'=>$form->createView()
        ]);
    }
//
//    /**
//     * @Route("/login", name="login")
//     */
//    public function loginAction(Request $request, AuthenticationUtils $authUtils)
//    {
//        // get the login error if there is one
//        $error = $authUtils->getLastAuthenticationError();
//
//        // last username entered by the user
//        $lastUsername = $authUtils->getLastUsername();
//        if (isset($error)) {
//            $this->addFlash(
//                'error',
//                'Gegevens kloppen niet. Probeer opnieuw.'
//            );
//        } else {
//
//            $this->addFlash(
//                'notice',
//                'Vul uw gegevens in'
//            );
//        }
//        return $this->render('bezoeker/login.html.twig', array(
//            'last_username' => $lastUsername,
//            'error'         => $error,
//        ));
//    }

}

templates/bezoeker/index.html.twig
{% extends 'bezoeker.html.twig' %}


{% block menu %}
    <li class="active"><a href="{{ path('homepage') }}">home</a></li>
    <li><a href="{{ path('kartactiviteiten') }}">aanbod</a></li>


    <li><a href="{{ path('registreren') }}">registreren</a></li>
    <li><a href="#">contact</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-4 hidden-xs">
            <div class="panel panel-primary">
                <div class="panel-heading">SODI SR4 Simply Stunning</div>
                <div class="panel-body">
                    <img class="img-responsive center-block" style="width:70%" src={{ asset('img/sodiLR4.png')}} />
                </div>
            </div>
        </div>
        <div class="col-sm-4 hidden-xs">
            <div class="panel panel-primary">
                <div class="panel-heading">SODI SR5 Comfort and Style</div>
                <div class="panel-body">
                    <img class="img-responsive center-block " style="width:70%" src={{ asset('img/sodiLR5.png')}} />
                </div>
            </div>
        </div>
        <div class="col-sm-4 hidden-xs">
            <div class="panel panel-primary">
                <div class="panel-heading">SODI 2DRIVE Dream Racer</div>
                <div class="panel-body">
                    <img class="img-responsive center-block " style="width:70%" src={{ asset('img/sodi2Drive.png')}} />
                </div>
            </div>
        </div>
    </div>

    <h4>Een schitterende sport </h4>

    Wil je met één of twee personen karten of ben je met een groep onder de 10 personen?
    Rij dan een Vrije Training. Een Vrije Training is een kart-heat (rit) van 15 minuten.
    Een Grand Prix of een Endurance race is leuk voor de echte kartfanaten, deze duren 60 min.
    Ervaar het ultieme racegevoel in een Kinder kart! Voor het karten krijgen kinderen (minimaal 8 jaar)
    eerst een briefing met een uitleg over de vlaggen en de werking van de kart.

    De karts hebben een 200 cc benzinemotor, zijn splinternieuw en voorzien van alle veiligheidsmaatregelen,
    zoals een rolbeugel en een 4-puntsgordel. Op de kartbaan rijden maximaal 14 karts.
    Let op, voor het karten zijn dichte schoenen verplicht. Tip: Karten met een korte broek is niet toegestaan.
    Wij hebben overalls ter beschikking, maar probeer indien mogelijk een lange broek aan te doen of mee te nemen.
{% endblock %}

templates/bezoeker/kartactiviteiten.html.twig
{% extends 'bezoeker.html.twig' %}
{% block menu %}
    <li><a href="{{ path('homepage') }}">home</a></li>
    <li class="active"><a href="{{ path('kartactiviteiten') }}">aanbod</a></li>
    <li><a href="{{ path('registreren') }}">registreren</a></li>
    <li><a href="#">contact</a></li>
{% endblock %}
{% block content %}
    <section >
        <article>
            <h3>Er zijn {{ soortactiviteiten|length }} soorten activiteiten </h3>
            <ul class="list-group">
                {% for activiteit in soortactiviteiten %}
                <li class="list-group-item text-primary">{{ activiteit.naam }}</li>
                {% endfor %}
            </ul>
            <p>
                Let op, voor het karten zijn dichte schoenen verplicht.
                Karten met een korte broek is niet toegestaan. Wij hebben overalls ter beschikking,
                maar probeer indien mogelijk een lange broek aan te doen of mee te nemen.
            </p>
        </article>
        <figure>
            <img class="img-responsive center-block" style="width:30%"src={{ asset('img/kart.jpg') }} alt="kart" />
        </figure>
    </section>
{% endblock %}

templates/bezoeker/login.html.twig
{% extends 'bezoeker.html.twig' %}

{% block menu %}
    <li><a href="{{ path('homepage') }}">home</a></li>
    <li><a href="{{ path('kartactiviteiten') }}">aanbod</a></li>
    <li><a href="{{ path('registreren') }}">registreren</a></li>
    <li><a href="#">contact</a></li>
{% endblock %}

{% block content %}
<form method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputUsername">Username</label>
    <input type="text" value="{{ last_username }}" name="username" id="inputUsername" class="form-control" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
{% endblock %}

templates/bezoeker/registreren.html.twig
{% extends 'bezoeker.html.twig' %}
{% form_theme form _self %}
{% block button_widget -%}
    {%- set attr = attr|merge({class: (attr.class|default('btn-primary') ~ ' btn')|trim}) -%}
    {%- if label is not same as(false) and label is empty -%}
        {%- if label_format is not empty -%}
            {% set label = label_format|replace({
            '%name%': name,
            '%id%': id,
            }) %}
        {%- else -%}
            {% set label = name|humanize %}
        {%- endif -%}
    {%- endif -%}
    <button type="{{ type|default('button') }}" {{ block('button_attributes') }}>{{ translation_domain is same as(false) ? label : label|trans({}, translation_domain) }}</button>

{%- endblock button_widget %}
{% block form_group_class -%}
    col-sm-6
{%- endblock form_group_class %}

{% block menu %}
    <li><a href="{{ path('homepage') }}">home</a></li>
    <li><a href="{{ path('kartactiviteiten') }}">aanbod</a></li>
    <li class="active"><a href="{{ path('registreren') }}">registreren</a></li>
    <li><a href="#">contact</a></li>
{% endblock %}

{% block content %}
    <h3>Registreren</h3>

    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}

{% endblock %}